local_costmap:
  global_frame: odom
  rolling_window: true
  width: 4
  height: 4
  resolution: 0.04
  static_map: false 

  inflation:
    enabled: true
    inflation_radius: 0.5

  plugins:
    - {name: obstacles_laser, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation, type: "costmap_2d::InflationLayer"}
